CAR_BRANDS = {
    1: 'mvm',
    2: 'bmw',
    3: 'brilliance',
    4: 'swm',
    5: 'besturn',
    6: 'mercedes-benz',
    7: 'borgward',
    8: 'pride',
    9: 'peugeot',
    10: 'toyota',
    11: 'tiba',
    12: 'geely',
    13: 'jac',
    14: 'changan',
    15: 'chery',
    16: 'dongfeng',
    17: 'dena',
    18: 'runna',
    19: 'renault',
    20: 'zotye',
    21: 'rigan',
    22: 'ssang-yong',
    23: 'lexus',
    25: 'kia',
    26: 'quick',
    27: 'capra',
    28: 'volkswagen',
    29: 'foton',
    30: 'citroen',
    31: 'suzuki',
    32: 'samand',
    33: 'saina',
    34: 'lifan',
    35: 'mazda',
    36: 'mitsubishi',
    37: 'mini',
    38: 'nissan',
    39: 'pick-up',
    40: 'haval',
    41: 'haima',
    42: 'hyundai',
}

MOBILE_BRANDS = {
    'اپل': 'https://www.digikala.com/search/category-mobile-phone/?has_selling_stock=1&q=%D8%A7%D9%BE%D9%84&sortby=20',
    'سامسونگ': 'https://www.digikala.com/search/category-mobile-phone/?has_selling_stock=1&q=%D8%B3%D8%A7%D9%85%D8%B3%D9%88%D9%86%DA%AF&pageno=1&sortby=20',
    'هواوی': 'https://www.digikala.com/huawei-brand/mobile-phone/?has_selling_stock=1&sortby=20',
    'شیائومی': 'https://www.digikala.com/search/category-mobile-phone/?has_selling_stock=1&q=%D8%B4%DB%8C%D8%A7%D8%A6%D9%88%D9%85%DB%8C&pageno=1&sortby=20'
}

CURRENCY_GOLD_NAME = {
    'دلار': ['usd1', 'usd2'],
    'روبل روسیه': ['rub1', 'rub2'],
    'دلار کانادا': ['cad1', 'cad2'],
    'یورو': ['euro1', 'euro2'],
    'لیر ترکیه': ['try1', 'try2'],
    'دینار عراق': ['iqd1', 'iqd1'],
    'دلار استرالیا': ['aud1', 'aud2'],
    'ریال قطر': ['qar1', 'aud2'],
    'دلار سنگاپور': ['sgd1', 'sgd2'],
    'آزادی': ['azadi1', 'azadi12'],
    'امامی': ['emami1', 'emami12'],
    'نیم سکه': ['azadi1_2', 'azadi1_22'],
    'ربع سکه': ['azadi1_4', 'azadi1_42'],
    'سکه گرمی': ['azadi1g', 'azadi1g2'],
}
